image: getto/hangar:AfNMyZFOJMbXMPot-20210202134653

stages:
  - image_build
  - image_push
  - bump_version
  - release
  - release_notify

variables:
  TRELLIS_HANGAR: https://trellis.getto.systems/hangar/3.5.0
  TRELLIS_GIT_POST: https://trellis.getto.systems/git/post/1.5.1
  TRELLIS_CI_BUMP_VERSION: https://trellis.getto.systems/ci/bump-version/1.10.1
  TRELLIS_PSYCHER_GETTO: https://trellis.getto.systems/psycher/getto/2.7.2

image_build:
  stage: image_build
  only:
    refs:
      - merge_requests
    changes:
      - Dockerfile
      - resources/*

  image: docker:stable

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

  services:
    - docker:dind

  artifacts:
    paths:
      - .build/image.tar.gz
    expire_in: 1 day

  before_script:
    - mkdir -p .build
    - export image=image:$CI_COMMIT_SHORT_SHA
  script:
    - docker build -t $image .
    - docker image save $image --output .build/image.tar
    - gzip .build/image.tar
    - chown 1000:1000 .build/image.tar.gz

image_push:
  stage: image_push
  only:
    refs:
      - release@getto-systems-base/labo/container/theia
    changes:
      - Dockerfile
      - resources/*
  except:
    refs:
      - schedules
      - triggers

  image: docker:stable

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

  services:
    - docker:dind

  before_script:
    - apk update && apk add bash git curl
    - git config user.email admin@getto.systems
    - git config user.name getto
    - curl $TRELLIS_GIT_POST/setup.sh | sh -s -- ./vendor/getto-systems
    - export HOME=$(pwd)
    - export PATH=$PATH:./vendor/getto-systems/git-post/bin
    - export hangar_id=$(cat .getto-hangar-image | sed 's/.*://' | sed 's/-.*//')
    - export image=getto/hangar:$hangar_id-$(date +%Y%m%d%H%M%S)
    - curl $TRELLIS_HANGAR/docker_login.sh | sh
  script:
    - docker build -t $image .
    - docker push $image
    - 'sed -i -e "s|image: getto/hangar:$hangar_id-\\?.*|image: $image|" .gitlab-ci.yml'
    - echo $image > .getto-hangar-image
    - 'git add .gitlab-ci.yml .getto-hangar-image && git commit -m "update: image"'
    - curl $TRELLIS_CI_BUMP_VERSION/request.sh | bash -s -- ./.ci/message/fix-image.sh

bump_version:
  stage: bump_version
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: buildpack-deps:buster-scm

  before_script:
    - git config user.email admin@getto.systems
    - git config user.name getto
    - curl $TRELLIS_GIT_POST/setup.sh | sh -s -- ./vendor/getto-systems
    - export PATH=$PATH:./vendor/getto-systems/git-post/bin
  script:
    - curl $TRELLIS_CI_BUMP_VERSION/bump_version.sh | bash
    - curl $TRELLIS_CI_BUMP_VERSION/request.sh | bash -s -- ./.ci/message/bump.sh

release:
  stage: release
  only:
    refs:
      - release@getto-systems-base/labo/container/theia
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules

  script:
    - curl $TRELLIS_CI_BUMP_VERSION/push_tags.sh | sh

release_success:
  stage: release_notify
  only:
    refs:
      - release@getto-systems-base/labo/container/theia
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_success

  image: buildpack-deps:buster-curl

  before_script:
    - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
    - export channel=$SLACK_CHANNEL
    - export version=theia:$(cat .release-version)
  script:
    - curl $TRELLIS_PSYCHER_GETTO/notify-release-success.sh | sh -s -- $url $channel $version

release_failure:
  stage: release_notify
  only:
    refs:
      - release@getto-systems-base/labo/container/theia
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_failure

  image: buildpack-deps:buster-curl

  before_script:
    - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
    - export channel=$SLACK_CHANNEL
    - export version=theia:$(cat .release-version)
  script:
    - curl $TRELLIS_PSYCHER_GETTO/notify-release-failure.sh | sh -s -- $url $channel $version
